# Generated by Django 4.2.1 on 2024-10-20 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("review_service", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="year_of_publish",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="review",
            name="book",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="review_book",
                to="review_service.book",
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="review_user",
                to="review_service.user",
            ),
        ),
    ]
