# Generated by Django 4.2.1 on 2024-10-20 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("review_service", "0002_book_year_of_publish_alter_review_book_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="password",
            field=models.CharField(default=None, max_length=128),
            preserve_default=False,
        ),
    ]
