# Generated by Django 4.2.1 on 2024-10-20 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("review_service", "0003_user_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="rating",
            field=models.FloatField(),
        ),
    ]
